### ISSUE TITLE
Can I use CloudFlare PageRules to cache Static HTML in WordPress?

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#117]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Can I use CloudFlare PageRules to cache static HTML in WordPress?
categories: questions
tags: cloudflare
author: raamdev
github-issue: 
```
---
CloudFlare can cache static HTML using their PageRules feature (see [this CloudFlare article](https://support.cloudflare.com/hc/en-us/articles/200172256-How-do-I-cache-static-HTML-)), but from the perspective of WordPress, nothing that WordPress produces is really "static HTML"; it's all dynamic HTML. For that reason, CloudFlare PageRules should not be used to cache WordPress.

Comet Cache _creates_ static HTML versions of the dynamic WordPress output and stores that in a cache file, which then gets served to new visitors, but the only reason that Comet Cache can serve static HTML versions of a WordPress site is that Comet Cache also dynamically integrates with WordPress itself and deletes outdated cache files whenever the dynamic content changes in some way. 

For example, if you modify a published post, publish a new post that appears on the home page, change your WordPress theme, or take any other action that changes what WordPress will display on the site, Comet Cache will automatically detect that event and then clear the necessary cache files so that future visitors are not presented with an old, outdated version of the site.

CloudFlare PageRules for caching static HTML is not designed for dynamic websites like WordPress. It is designed for actual static HTML, where there is nothing dynamic that is producing the HTML. For that reason, CloudFlare PageRules should not be used in a dynamic environment like WordPress.

**Comment by 123conecta** [comment]
Hi @raamdev , how effective would be to either create a rule to cache the content created by cometcahce inside cloudflare? Or to "push the content created by the plugin to cloudflare via API?
any thoughts on that? I am willing to test, cheers

**Comment by raamdev** [comment]
@123conecta Comet Cache simply creates an HTML file containing the output of a given request and then serves that instead of loading all of WordPress to serve the request, so you could certainly cache that same page in CloudFlare. 

However, as explained in [the article linked to above](https://cometcache.com/kb-article/can-i-use-cloudflare-pagerules-to-cache-static-html-in-wordpress/), WordPress is very dynamic, so if you cached a post in CloudFlare and then, for example, updated that post, you'd need some way to tell CloudFlare that the content for that post is now outdated and the cache needs to be cleared. Comet Cache handles this automatically by hooking into various parts of WordPress and intelligently clears the necessary cache files (as opposed to clearing the entire cache).

I haven't looked into the CloudFlare API, but I suppose it might be possible to build an integration between Comet Cache and CloudFlare so that when the cache for a specific thing needs to be cleared, Comet Cache clears the local cache + the appropriate CloudFlare cache, but that sort of integration goes a bit out of scope for what Comet Cache is designed for and would require maintaining API compatibility between Comet Cache and CloudFlare in the future.

I'm no longer working on the Comet Cache project, so I'm pinging @clavaque here so that he's aware of this discussion.

**Comment by 123conecta** [comment]
Hi @raamdev , thanks for your reply.
