### ISSUE TITLE
Why doesn't the HTML Compressor compress all CSS / JavaScript?

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#119]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ cometcache.com<br />:page_with_curl: See: [Why doesn't the HTML Compressor compress all CSS / JavaScript?](http://cometcache.com/kb-article/why-doesnt-the-html-compressor-compress-all-css-javascript/)
[:octocat: View Markdown File](https://github.com/websharks/comet-cache-kb/blob/master/questions/2016/119-why-doesnt-the-html-compressor-compress-all-css-javascript.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/comet-cache-kb/edit/master/questions/2016/119-why-doesnt-the-html-compressor-compress-all-css-javascript.md)

---

**Comment by Reedyseth** [comment]
@raamdev Would you mind to share on the Exclusion Patterns screenshot some examples so that the users that are not very experienced have a small clue ?

**Comment by raamdev** [comment]
@Reedyseth I updated the article to include a link to the [Watered-Down Regex Syntax](https://cometcache.com/kb-article/watered-down-regex-syntax/) article, which includes examples. Thank you for the suggestion!
