### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by renzms** [websharks/comet-cache-kb#120]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Frequently Asked Questions
categories: questions
tags: 
author: renzms
github-issue: https://github.com/websharks/comet-cache-kb/issues/120
```
---

## Table of Contents

- [Why is my cache directory empty?](#why-is-my-cache-directory-empty)
- [Why doesn't Comet Cache eliminate render-blocking JavaScript and CSS in above-the-fold content?](#why-doesnt-comet-cache-eliminate-render-blocking-javascript-and-css-in-above-the-fold-content)
- [How can I show dynamic content while caching the page?](#how-can-I-show-dynamic-content-while-caching-the-page)
- [How can I exclude the Home Page from being cached?](#how-can-I-exclude-the-home-page-from-being-cached)

## Why is my cache directory empty?

See [Why is my cache directory empty?](https://github.com/websharks/comet-cache-kb/issues/123)

### How can I prevent the cache from being cleared automatically?

See [Disabling Automatic Clear / Wipe Cache Routines](https://cometcache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/)

## Why doesn't Comet Cache eliminate render-blocking JavaScript and CSS in above-the-fold content?

See [Why doesn’t Comet Cache “Eliminate Render Blocking” and move CSS/JS scripts into the footer?](https://cometcache.com/kb-article/why-doesnt-comet-cache-eliminate-render-blocking-and-move-cssjs-scripts-into-the-footer/)

## How can I show dynamic content while caching the page?

 See [How can I show dynamic content while caching the page?](https://github.com/websharks/comet-cache-kb/issues/124).

## How can I exclude the Home Page from being cached?

 See [How can I exclude the Home Page from being cached?](https://github.com/websharks/comet-cache-kb/issues/125).

**Comment by raamdev** [comment]
@renzms As I mentioned in https://github.com/websharks/cometcache.com/issues/97#issuecomment-232437828, each of the questions above should be their own KBA.

**Comment by renzms** [comment]
@raamdev 

Updated with links to existing KBA equivalents and drafts.

**Comment by raamdev** [comment]
@renzms Yes. Thanks!
