### ISSUE TITLE
Why is my cache directory empty?

### ISSUE THREAD

**Issue by renzms** [websharks/comet-cache-kb#123]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why is my cache directory empty?
categories: questions
tags: clearing-the-cache
author: renzms
github-issue: https://github.com/websharks/comet-cache-kb/issues/123
```
---

If your cache directory is empty, it could mean that Comet Cache isn't enabled (See: **Dashboard → Comet Cache → Enable/Disable**) or that there is an error occurring behind the scenes that is preventing Comet Cache from operating normally.

If Comet Cache is running properly, then an empty cache directory could indicate that Comet Cache has not generated any cache files. Comet Cache will generate cache files when the plugin is active and a visitor visits your site while not logged in (unless you have Caching for Logged-In Users enabled--Pro version only).

An empty cache directory could also mean that all of the cache files passed their expiration date (See: **Dashboard → Comet Cache → Directory / Expiration Time**) or that Comet Cache recently cleared the entire cache automatically. 

There are a number of reasons why Comet Cache might clear the entire cache directory automatically: 

- You upgraded Comet Cache
- You restored the Comet Cache default settings
- You changed the WordPress theme
- You changed navigation menus
- You changed Links (you may or may not have the [Links SubPanel](https://codex.wordpress.org/Add_Link_SubPanel) on your site)
- You made changes to terms, e.g., Categories or Tags

Comet Cache automatically clears the cache when these events take place because not doing so would likely yield unexpected results. For example, if you modified your navigation menu and Comet Cache didn't clear the entire cache, visitors would be served cache files that included the old menu. Or if you changed your WordPress theme and didn't clear the cache, the old cache files would include the markup for the old theme. And so on.

If you find that none of the above scenarios are true and Comet Cache still has an empty cache directory, you should verify if [Comet Cache is working](https://cometcache.com/kb-article/how-do-i-know-if-comet-cache-is-working/).

**Comment by renzms** [comment]
@raamdev 

Added tags and updated the article, let me know if there's anything else needed, thanks!

**Comment by jaswsinc** [comment]
Nice! Looks great to me.

**Comment by raamdev** [comment]
@renzms Nice! I would add a final paragraph to the bottom that says if none of the above are true, you should make sure Comet Cache is working (link to [How do I know if Comet Cache is working?](https://cometcache.com/kb-article/how-do-i-know-if-comet-cache-is-working/)).

**Comment by renzms** [comment]
@raamdev 
> I would add a final paragraph to the bottom that says if none of the above are true, you should make sure Comet Cache is working (link to How do I know if Comet Cache is working?).

I added a sentence at the end, should I expand that further into a full paragraph?
