### ISSUE TITLE
How can I show dynamic content while caching the page?

### ISSUE THREAD

**Issue by renzms** [websharks/comet-cache-kb#124]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ cometcache.com<br />:page_with_curl: See: [How can I show dynamic content while caching the page?](http://cometcache.com/kb-article/how-can-i-show-dynamic-content-while-caching-the-page/)
[:octocat: View Markdown File](https://github.com/websharks/comet-cache-kb/blob/master/questions/2016/124-how-can-i-show-dynamic-content-while-caching-the-page.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/comet-cache-kb/edit/master/questions/2016/124-how-can-i-show-dynamic-content-while-caching-the-page.md)

---

**Comment by renzms** [comment]
@raamdev 

Added tags and updated the article, let me know if there's anything else needed, thanks!

**Comment by jaswsinc** [comment]
> that is being cached (a Page View Counter widget on the Home Page, for example)

For improved clarity, I suggest starting this bracketed example with the words `(e.g., `) to indicate it's an example that you're giving when you start reading it, instead of say, `, for example` at the end of the sentence.

> content (a counter, for example)

This is fine, because it is short. The longer example is harder to figure out.

> With Comet Cache Lite, you will need to write some PHP code in your wp-config.php file to dynamically detect the page with the dynamic content and then set define(COMET_CACHE_ALLOWED, FALSE); to prevent Comet Cache from caching that particular page.

I suggest excluding this 'lite' solution from the article, as it requires custom code which is unnecessary when you upgrade to pro. Our objective should be to sell pro features whenever we can, and this is a great opportunity to do that.

**Comment by raamdev** [comment]
> With Comet Cache Pro this can be done using the URI Exclusion Patterns feature

That is no longer true. **URI Exclusion Patterns** are available in the Lite version now (it used to be a Pro-only feature, but its been a Lite feature for over a year now).

**Comment by renzms** [comment]
@jaswsinc @raamdev 

Updated according to your notes, thanks!
