### ISSUE TITLE
Is Comet Cache compatible with iThemes Security?

### ISSUE THREAD

**Issue by renzms** [websharks/comet-cache-kb#130]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

```yaml
title: Is Comet Cache compatible with iThemes Security?
categories: questions
tags: themeplugin-developers, troubleshooting
author: renzms
github-issue: https://github.com/websharks/comet-cache-kb/issues/130
```

---

Yes, Comet Cache is compatible with iThemes Security and other WordPress security plugins that may block access to protect sensitive portions of a WordPress site.

WordPress plugins, such as iThemes Security, may block parts of the WordPress site, including the back-end administration, thus preventing unauthorized visitors from accessing these areas. iThemes Security may also tweak certain features on the Dashboard and/or host file settings for increased security. Comet Cache causes no conflict with iThemes Security in this regard, and enabling most of the recommended settings in the Lite version of iThemes Security has no reported issues with the caching process.

There is no specific set of features needed to configure Comet Cache with iThemes Security.

### What if iThemes Security constantly warns me when Comet Cache caches or clears files?

iThemes Security and other WordPress security plugins may log changes to your site files and notify you of these changes. Comet Cache is a dynamic plugin that quietly caches pages, and depending on your specified configuration(s), it is able to automatically clear, wipe or update the cache on a specified date or upon a triggered event. These changes may alert the security plugin as unsolicited changes. These notifications are a false-positive, and iThemes Security may continue to log these events multiple times.

This can be solved in iThemes Security by adding the cache folder as an exclusion in the `File Change Detection` settings.

>![2017-01-19_20-53-46](https://cloud.githubusercontent.com/assets/13220018/22107756/9a457ce8-de8a-11e6-9488-5b77db28fa39.png)

In the pop-up window, scroll down to the` Files and Folders List` section. Exclude files or folders by clicking the red minus next to the file or folder name. We suggest whitelisting `wp-content/cache/comet-cache/`, or you could whitelist the entire cache directory; i.e., `wp-content/cache`.

>![2017-01-19_21-07-00](https://cloud.githubusercontent.com/assets/13220018/22107874/506866ca-de8b-11e6-97b8-411fcbd07655.png)

**Comment by renzms** [comment]
@raamdev 

Hi Raam! Could you please check my draft? 

Any suggestions for additional screenshots or sections?

**Comment by raamdev** [comment]
@renzms Fantastic! This is 99% perfect. :-) The only spelling correction I caught was "false positive" should be "false-positive". Also, in the screenshot you took, if you could take a larger screenshot that shows where in iThemes Security that section is and also select the `wp-content/cache/comet-cache/` directory instead of `wp-content/cache/comet-cache/cache/https/`, that would be great.

**Comment by jaswsinc** [comment]
Nice work @renzms!!

I agree with Raam. Back up one directory and suggest whitelisting `wp-content/cache/comet-cache/cache`, or for that matter, I would whitelist the entire cache directory if it were my installed; i.e., `wp-content/cache` and `wp-content/uploads` too.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Thanks for the suggestions and fixes. :)

Changelog 

- updated spelling to `false-positive` 
- updated `Detection File Settings` to `File Change Detection` to better reflect name of panel.
- included two new screenshots 
>1. to show the options list to illustrate where to go 
>2. a full shot of the pop-up of the Configuration Settings
>>a. screenshot now reflects proper path of `wp-content/cache/comet-cache/` directory instead of `wp-content/cache/comet-cache/cache/https/`
- added suggestion to whitelist `wp-content/cache/comet-cache/cache` and Jason's suggest to take that a step further and whitelist `wp-content/cache`
