### ISSUE TITLE
How do I change the cache locking type (flock vs sem_get)?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comet-cache-kb#16]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Incorporate the details I discussed [here](https://github.com/websharks/quick-cache/issues/373#issuecomment-65520009).

---

### KB Article Published @ cometcache.com<br />:page_with_curl: See: [How do I change the cache locking type (flock vs sem_get)?](http://cometcache.com/kb-article/how-do-i-change-the-cache-locking-type-flock-vs-sem_get/)
[:octocat: View Markdown File](https://github.com/websharks/comet-cache-kb/blob/master/questions/2016/16-how-do-i-change-the-cache-locking-type-flock-vs-sem_get.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/comet-cache-kb/edit/master/questions/2016/16-how-do-i-change-the-cache-locking-type-flock-vs-sem_get.md)

---

**Comment by jaswsinc** [comment]
Referencing: https://github.com/websharks/quick-cache/issues/373#issuecomment-65520009

**Comment by jaswsinc** [comment]
Updating `zc-hacks.php` to `zc-cache-lock-type.php`.

**Comment by raamdev** [comment]
Updated the title to `How can I change the cache locking type (flock vs sem_get)?`

**Comment by raamdev** [comment]
> Incorporate the details I discussed [here](https://github.com/websharks/quick-cache/issues/373#issuecomment-65520009).

I suggest we create a separate KB Article called "What is cache locking?" that includes those extra details. We can then trim this KB Article down a bit and move the explanations to the other KB Article.

**Comment by jaswsinc** [comment]
Copy that. I started writing another article about this here: https://github.com/websharks/zencache-kb/issues/36

**Comment by jaswsinc** [comment]
I was just reviewing this. The above ↑ is correct.

```php
<?php
add_filter('zencache\\share::cache_lock_lock_type', function(){
    return 'sem';
});
```

## After Restructure Is Complete

- The preferred filter name will be: `zencache_cache_lock_type`  
  _The old filter name will continue to work however._

```php
<?php
add_filter('zencache_cache_lock_type', function($type = 'flock'){
    return 'sem';
});
```
