### ISSUE TITLE
How can I run the Auto-Cache Engine manually?

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#81]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [How can I run the Auto-Cache Engine manually?](http://zencache.com/kb-article/how-can-i-run-the-auto-cache-engine-manually/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/81-how-can-i-run-the-auto-cache-engine-manually.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/81-how-can-i-run-the-auto-cache-engine-manually.md)

---

**Comment by GermontZ** [comment]
I disabled autoloading of wp-cron.php, and setup a cronjob 4 times a day for it in cpanel.
What could be the best method to call your autocache engine from cPanel every 15 minutes?
I found examples both with GET, others with wget... Is it a typo?
I would really appreciate if you could provide a few examples in your article. Thank you!

**Comment by jaswsinc** [comment]
Example of a cURL CRON job:

```bash
curl http://example.com/?comet_cache_auto_cache_cron=1 -so /dev/null
```

**Comment by jaswsinc** [comment]
Nice! :-)
